Event loop
fcitx-contrib/fcitx5-macos pull request #16
Opened 2024-01-11 08:47 UTC by ksqsf

Not 100% certain of thread-safety yet.

2024-01-11 13:50 UTC, ksqsf commented
~~Found a bug. Do not merge. Debugging...~~ Should be fixed now!

2024-01-12 02:39 UTC, eagleoflqj requested changes

2024-01-12 02:39 UTC, eagleoflqj commented on macosfrontend/macosfrontend.cpp
>      icTable_.erase(cookie);
In the worst case, the cookie is looked up 3 times. Checking, fetching and removing can be achieved in 1 pass using `find`.

2024-01-12 02:39 UTC, eagleoflqj commented on src/fcitx.cpp
> -    // Separate plugins so that dmg replacement won't remove them
Keep these coments.

2024-01-12 02:39 UTC, eagleoflqj commented on src/fcitx.h
> +#pragma once
👍

2024-01-12 02:39 UTC, eagleoflqj commented on src/fcitx.h
> +    friend void start_fcitx_thread();
Not needed.

2024-01-12 02:39 UTC, eagleoflqj commented on src/fcitx.cpp
> +    return dynamic_cast<fcitx::MacosFrontend *>(addon("macosfrontend"));
`macosfrontend` is frequently used, but every call to `addon` queries a map.
https://github.com/fcitx/fcitx5/blob/b56322a85dbc06d74dc855770971d642f69b662e/src/lib/fcitx/addonmanager.cpp#L67
The function could be kept, but the result of `addon("macosfrontend")` should be cached.

2024-01-12 04:08 UTC, eagleoflqj approved these changes
Tested with lldb. `RimeEngine::rimeNotificationHandler` is hit on Shift.
Thanks for separating threads.

2024-01-12 04:09 UTC, merged

2024-01-12 04:52 UTC, ksqsf commented
Note: `showPreedit` and `commit` were wrapped in `DispatchQueue.main.async` at first (https://github.com/fcitx-contrib/fcitx5-macos/pull/16/commits/e1f3049cf8cc88a8ecb774a1d5424d1ff138268a), but due to issues with iTerm2, it was reverted (https://github.com/fcitx-contrib/fcitx5-macos/pull/16/commits/a37816150329876a62c804c60915cfa5908167f8). This is harmless according to my local tests, but further investigation can be helpful.